version: '3.3'
services:
    rpi-monitor:
        devices:
            - /dev/vchiq
            - /dev/vcsm
        volumes:
            - '/opt/vc:/opt/vc'
            - '/boot:/boot'
            - '/sys:/dockerhost/sys:ro'
            - '/etc:/dockerhost/etc:ro'
            - '/proc:/dockerhost/proc:ro'
            - '/usr/lib:/dockerhost/usr/lib:ro'
        ports:
            - '8888:8888'
        container_name: rpi-monitor
        image: 'michaelmiklis/rpi-monitor:latest'