version: '3'
services:

    timescaledb:
        image: 'timescale/timescaledb:latest-pg12'
        container_name: 'dih4cps-timescale-container'
        restart: always
        environment:
        - POSTGRES_DB=dih4cpsdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        volumes:
        - ../subsystems/data/ts_data/init.sql:/docker-entrypoint-initdb.d/init.sql
        - timescale_data:/var/lib/postgresql/data
        ports:
        - '5432:5432'
        healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 5s

volumes:
    timescale_data:
          