version: '3'
services:

    timescaledb:
        image: 'timescale/timescaledb:latest-pg12'
        container_name: 'timescale-container'
        restart: always
        environment:
        - POSTGRES_DB=Databasepostres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        volumes:
       # - ../subsystems/data/ts_data/init.sql:/docker-entrypoint-initdb.d/init.sql
        - timescale_data:/var/lib/postgresql/data
        ports:
        - '5432:5432'


volumes:
    timescale_data:
          