version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
    logging:
        options:
            max-size: 10m
            max-file: "3"
    ports:
        - '5438:5432'
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
