version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.6.0
    depends_on:
      - postgres
      - minio
    command: >
      mlflow server --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow \
                   --default-artifact-root s3://mlflow/ --host 0.0.0.0 --port 5000
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    ports:
      - "5000:5000"

  jupyter:
    image: jupyter/scipy-notebook
    environment:
      JUPYTER_TOKEN: mlops
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"

volumes:
  postgres_data:
  minio_data:
