version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    deploy:
        resources:
          limits:
            cpus: "0.50"
            memory: "256M"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      # WEBPASSWORD: 'Añade tu contraseña'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: always
    hostname: pihole