stages:
  - sonar

# SonarQube
sonar:
 stage: sonar
 image:
   name: sonarsource/sonar-scanner-cli:latest
   entrypoint: [ "" ]
 variables:
   SONAR_TOKEN: "${SONAR_TOKEN}"
   SONAR_URL: "${SONAR_URL}"
 script:
   - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=Mes -Dsonar.sources=. -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN} 

